name: Workflow B

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use data from Workflow A
        run: |
          echo "Data received: ${{ github.event.inputs.data }}"
