name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：设置 JDK 版本
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # 步骤3：构建项目
      - name: Build with Maven
        run: mvn package

      # 步骤4：上传构建产物
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/ethStats.jar

      # 步骤5：更新 Releases
      - name: Update Release
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}
          RELEASE_ID=YOUR_RELEASE_ID  # 替换为实际的 Release ID
          TAG_NAME=v1.0.0  # 替换为实际的标签名称
          RELEASE_NAME=v1.0.0  # 替换为实际的 Release 名称

          # 使用 curl 或其他适合的工具发送 API 请求
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/releases/$RELEASE_ID \
            -d '{
              "tag_name": "'$TAG_NAME'",
              "name": "'$RELEASE_NAME'",
              "body": "Your release notes for the updated version."
            }'
