name: Build and Update Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Get Release
        id: get_release
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const tagName = 'v1.0.0';

            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner,
              repo,
              tag: tagName,
            });

            return release.id;

      - name: Upload Release Asset
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const artifactPath = 'target/ethStats.jar';  // Change this to your artifact path
            const artifactName = 'ethStats.jar';  // Change this to your artifact's name
            const uploadUrl = `https://uploads.github.com/repos/${context.repo.owner}/${context.repo.repo}/releases/${steps.get_release.outputs.result}/assets{?name,label}`;
            const file = fs.readFileSync(artifactPath);

            const { data } = await github.repos.uploadReleaseAsset({
              url: uploadUrl,
              headers: {
                'content-length': file.length,
                'content-type': 'application/zip',
              },
              name: artifactName,
              file: file
            });

            if (data.browser_download_url) {
              core.info(`Uploaded release asset: ${data.browser_download_url}`);
            } else {
              core.setFailed('Failed to upload release asset');
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
