name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：设置 JDK 版本
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # 步骤3：构建项目
      - name: Build with Maven
        run: mvn package

      # 步骤4：上传构建产物
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/ethStats.jar

      # 步骤5：安装 @octokit/core
      - name: Install @octokit/core
        run: npm install @octokit/core

      # 步骤6：更新 Releases
      - name: Upload Release Asset
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const artifactPath = 'target/my-artifact.jar';  // Change this to your artifact path
            const artifactName = 'my-artifact.jar';  // Change this to your artifact's name
            const uploadUrl = '${{ steps.create_release.outputs.upload_url }}';
            const file = fs.readFileSync(artifactPath);

            const { data } = await github.repos.uploadReleaseAsset({
              url: uploadUrl,
              headers: {
                'content-length': file.length,
                'content-type': 'application/zip',
              },
              name: artifactName,
              file: file
            });

            if (data.url) {
              core.info(`Uploaded release asset: ${data.url}`);
            } else {
              core.setFailed('Failed to upload release asset');
            }
