name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：设置 JDK 版本
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # 步骤3：构建项目
      - name: Build with Maven
        run: mvn package

      # 步骤4：上传构建产物
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/ethStats.jar

      # 步骤5：更新 Releases
      - name: Update Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const owner = process.env.GITHUB_REPOSITORY.split("/")[0];
            const repo = process.env.GITHUB_REPOSITORY.split("/")[1];
            const tag = "v1.0.0"; // 更新的标签名称
            const releaseName = "v1.0.0"; // 更新的 Release 名称

            octokit.request('PATCH /repos/{owner}/{repo}/releases/{release_id}', {
              owner: owner,
              repo: repo,
              release_id: context.payload.release.id,
              tag_name: tag,
              name: releaseName,
              body: 'Your release notes for the updated version.'
            });
