name: ethStats

on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download jar file
        run: |
          wget https://github.com/sunchengzhu/eth-performance/releases/download/v1.0.0/ethStats.jar

      - name: Run jar file
        run: |
          nohup java -jar ethStats.jar &

      - name: Delay
        run: |
          sleep 5  # you may need more complex logic here to ensure the service is ready

      - name: Append to commands.txt
        run: |
          echo "printBlockNumber" >> commands.txt
          cat commands.txt