name: ethStats

on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download jar file
        run: |
          wget https://github.com/sunchengzhu/eth-performance/releases/download/v1.0.0/ethStats.jar

      - name: Run commands concurrently
        run: |
          (java -jar ethStats.jar; echo "Java command finished with exit code $?") &
          PID1=$!
          (echo "printBlockNumber" >> commands.txt; echo "Echo command finished with exit code $?") &
          PID2=$!
          wait $PID1 $PID2
