name: Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Package with Maven
        run: mvn clean package

      - name: Get release ID
        id: get_release_id
        run: |
          echo "::set-output name=release_id::$(curl --silent "https://api.github.com/repos/sunchengzhu/eth-performance/releases/tags/v1.0.0" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" | jq -r .id)"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get assets
        id: get_assets
        run: |
          assets_ids=$(curl --silent "https://api.github.com/repos/sunchengzhu/eth-performance/releases/tags/v1.0.0" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" | jq -r '.assets[].id')
          echo "assets_ids=${assets_ids}" >> $GITHUB_ENV
          echo "${assets_ids}"

      - name: Delete old release assets
        run: |
          for asset_id in ${assets_ids}; do
            curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/sunchengzhu/eth-performance/releases/assets/$asset_id
          done

      - name: Upload new release asset
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
               -H "Content-Type: application/zip" \
               -H "Accept: application/vnd.github.v3+json" \
               --data-binary @./target/ethStats.jar \
               "https://uploads.github.com/repos/sunchengzhu/eth-performance/releases/${{ steps.get_release_id.outputs.release_id }}/assets?name=ethStats.jar"

