name: Read Gist

on:
  workflow_dispatch:

jobs:
  read_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download jar file
        run: |
          wget https://github.com/sunchengzhu/eth-performance/releases/download/v1.0.0/ethStats.jar

      - name: Run ethStats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5ad4ca3b06f39c2d56cd2b1aa8f25204
        run: |
          (java -jar ethStats.jar | tee ethStats.log) &

      - name: Monitor gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5ad4ca3b06f39c2d56cd2b1aa8f25204
        run: |
          PREV_GIST_CONTENT=""
          while true; do
            sleep 5
            GIST_CONTENT=$(curl -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID | jq -r '.files["commands.txt"].content')
            if [ "$GIST_CONTENT" != "$PREV_GIST_CONTENT" ]; then
              echo $GIST_CONTENT >> commands.txt
              PREV_GIST_CONTENT=$GIST_CONTENT
            fi
            if [ "$GIST_CONTENT" == "successRate" ]; then
              break
            fi
          done

      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            commands.txt
            tps.csv
            performance.csv