name: Single EthStats

on:
  workflow_dispatch:
    inputs:
      jarArg:
        description: 'The argument to pass to the Java jar command'
        required: false
      tpsDuration:
        description: 'Duration of TPS function execution in minutes'
        required: false
        default: '2'

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download jar file
        run: |
          wget https://github.com/sunchengzhu/eth-performance/releases/download/v1.0.0/ethStats.jar

      - name: Run and Check Logs
        run: |
          nohup java -jar ethStats.jar ${{ github.event.inputs.jarArg }} > ./ethStats.out 2>&1 &
          JAVA_PID=$!
          
          tail -f ethStats.out &
          
          echo "tps" >> commands.txt
          sleep $(( ${{ github.event.inputs.tpsDuration }} * 60 ))
          echo "stopTps" >> commands.txt
          echo "successRate" >> commands.txt
          
          wait $JAVA_PID
          kill $TAIL_PID
          
          tail ethStats.out | while read LOGLINE
          do
          [[ "${LOGLINE}" == *"JVM正在退出"* ]] && echo "Detected JVM exit log entry."
          done
          tail -n 2 ethStats.out

      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            commands.txt
            ethStats.out
            tps.csv
            performance.csv