name: Write Gist

on:
  workflow_dispatch:
    inputs:
      tpsDuration:
        description: 'Duration of TPS function execution in minutes'
        required: false
        default: '1'

jobs:
  write_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: da9267c157dde31ce7e249713e23aa4f
        run: |
          update_gist() {
            cmd=$1
            JSON_DATA=$(printf '{"description": "Updated gist","files": {"commands.txt": {"content": "%s"}}}' "$cmd")
            curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d "${JSON_DATA}"
          }

          update_gist "tps"

          sleep $(( ${{ github.event.inputs.tpsDuration }} * 60 ))
          update_gist "stopTps"

          sleep 5
          update_gist "successRate"

          sleep 5
          update_gist "printBlockNumber"
