name: Write Gist

on:
  workflow_dispatch:

jobs:
  write_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # https://gist.github.com/sunchengzhu/5ad4ca3b06f39c2d56cd2b1aa8f25204
          GIST_ID: 5ad4ca3b06f39c2d56cd2b1aa8f25204
        run: |
          echo "" > commands.txt
          echo "printBlockNumber" >> commands.txt
          curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d @- << EOF
          {
            "description": "Updated gist",
            "files": {
              "commands.txt": {
                "content": "$(cat commands.txt)"
              }
            }
          }
          EOF
          sleep 30
          echo "successRate" >> commands.txt
          curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d @- << EOF
          {
            "description": "Updated gist",
            "files": {
              "commands.txt": {
                "content": "$(cat commands.txt)"
              }
            }
          }
          EOF
