name: Write Gist

on:
  workflow_dispatch:

jobs:
  write_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5ad4ca3b06f39c2d56cd2b1aa8f25204
        run: |
          function update_gist {
            curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d @- << EOF
            {
              "description": "Updated gist",
              "files": {
                "commands.txt": {
                  "content": "$(cat commands.txt)"
                }
              }
            }
            EOF
          }

          sleep 10
          echo "tps" > commands.txt
          update_gist

          sleep 60
          echo "stopTps" > commands.txt
          update_gist

          sleep 10
          echo "successRate" > commands.txt
          update_gist

          sleep 10
          echo "printBlockNumber" > commands.txt
          update_gist
