name: Write Gist

on:
  workflow_dispatch:
    inputs:
      tpsDuration:
        description: 'Duration of TPS function execution in minutes'
        required: false
        default: '1'

jobs:
  write_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5ad4ca3b06f39c2d56cd2b1aa8f25204
        run: |
          function update_gist {
            JSON_DATA=$(printf '{"description": "Updated gist","files": {"commands.txt": {"content": "%s"}}}' "$(cat commands.txt)")
            curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d "${JSON_DATA}"
          }

          sleep 3
          echo "tps" > commands.txt
          update_gist

          sleep $(( ${{ github.event.inputs.tpsDuration }} * 60 ))
          echo "stopTps" > commands.txt
          update_gist

          sleep 5
          echo "successRate" > commands.txt
          update_gist

          sleep 5
          echo "printBlockNumber" > commands.txt
          update_gist
